application: fawn-monitor
version: 1
runtime: python27
api_version: 1
threadsafe: true
handlers:  
- url: /
  static_files: html/index.html
  upload: html/index.html
  
- url: /fawn
  script: util.application

- url: /fdacs
  script: util.application  
  
- url: /index\.html
  static_files: html/index.html
  upload: html/index.html
  
- url: /fawn/monitor
  script: monitor.application
  
- url: /fdacs/monitor
  script: monitor.application
  
- url: /fawn/queryLastRecord
  script: util.application

- url: /fawn/queryRecord
  script: util.application
  
- url: /fdacs/queryLastRecord
  script: util.application

- url: /fdacs/queryRecord
  script: util.application  
  
- url: /js
  static_dir: js
  

  