#application: fawn-monitor
#version: 1
runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: ssl
  version: 2.7.11
handlers:  
- url: /
  static_files: html/index.html
  upload: html/index.html
  
- url: /fawn
  script: util.application

- url: /fdacs
  script: util.application  
  
- url: /index\.html
  static_files: html/index.html
  upload: html/index.html
  
- url: /fawn/monitor
  script: monitor.application
  
- url: /fdacs/monitor
  script: monitor.application
  
- url: /fawn/queryLastRecord
  script: util.application

- url: /fawn/queryRecord
  script: util.application
  
- url: /fdacs/queryLastRecord
  script: util.application

- url: /fdacs/queryRecord
  script: util.application  
  
- url: /js
  static_dir: js
  
- url: /fdacs/routine_vendor_email
  script: monitor.application

- url: /request/agtronix
  script: request.application

- url: /request/locher
  script: request.application

- url: /request/rainwise
  script: request.application

- url: /request/spectrum
  script: request.application

- url: /fdacs/unfixed_email
  script: monitor.application